# Generated by Django 2.0.1 on 2021-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210523_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='latitude',
            field=models.FloatField(default=14.6488),
        ),
        migrations.AddField(
            model_name='storebranch',
            name='longitude',
            field=models.FloatField(default=121.0509),
        ),
    ]
