# Generated by Django 2.0.1 on 2021-05-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('queue_hour', models.IntegerField(default=0)),
                ('queue_no', models.IntegerField(default=0)),
                ('queue_sub', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='small', max_length=15)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('account_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountBarcode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
