# Generated by Django 2.0.1 on 2021-06-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_branchopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchopening',
            name='max_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branchopening',
            name='min_customers',
            field=models.IntegerField(default=0),
        ),
    ]
